### ISSUE TITLE
Rocketlaunch media folders match + rename

### ISSUE THREAD

**Issue by horseyhorsey** [horseyhorsey/Hypermint.2.0#117]
Removed for better description below.

**Comment by ninja2bceen** [comment]
Use case

As a user I want to ensure that the rl folder names match database names. When they don't, the media does not display

Requirements

Ability to check to determine if the game folders within rl media folder names match the names found in Hyperspins wheel art folders or the database names or even the rom names

Determine which folder names within rl media folder does not match and which do match 

Ability to rename rl media folder names to match what the wheel art names are or database names or rom file names are. Whatever is easiest

Ability to match folder names within rl media folder against properly names media and match if greater than or equal to 65% of the name. So I guess the ability to change the confidence of how close the names have to be before renaming

Thank you! Please let me know if you need paths and such

The best example would be say you have within the rl media folder >sega Genesis> sonic and within you have the fade art etc. the only thing that is not correct is the folder name since the database name is sonic (USA). In order for the rl media to appear, the sonic folder needs to be renamed to sonic (USA).
